#ifndef COMMUNICATION_CODES_H_
#define COMMUNICATION_CODES_H_


#define PASSWORD_SIZE 3
#define PASSWORDS_MATCH 0x01
#define PASSWORDS_DONOT_MATCH 0x00
#define WRONG_PASSWORD '&'
#define CORRECT_PASSWORD '%'



#endif /* COMMUNICATION_CODES_H_ */
